server:
  port: 8887

logging:
  level:
    org:
      springframework:
        boot:
          # 오류만 출력
          autoconfigure: ERROR

spring:
  application:
    name: provider

  ## PostgreSQL 설정
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/dechator
    driver-class-name: org.postgresql.Driver
    username: dechator
    password: ''
    show-sql: true
    connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: HikariCP
      minimumIdle: 5
      maximumPoolSize: 50
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000

google:
  gemimiApiKey: ""